# Generated by Django 5.1 on 2024-11-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='PurchaseToken',
        ),
    ]
