# Generated by Django 5.1 on 2024-11-01 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_token_purchasetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
